USE [master]
GO
/****** Object:  Database [PBL]    Script Date: 6/9/2024 9:58:07 AM ******/
CREATE DATABASE [PBL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PBL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PBL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PBL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PBL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PBL] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PBL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PBL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PBL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PBL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PBL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PBL] SET ARITHABORT OFF 
GO
ALTER DATABASE [PBL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PBL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PBL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PBL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PBL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PBL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PBL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PBL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PBL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PBL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PBL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PBL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PBL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PBL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PBL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PBL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PBL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PBL] SET RECOVERY FULL 
GO
ALTER DATABASE [PBL] SET  MULTI_USER 
GO
ALTER DATABASE [PBL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PBL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PBL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PBL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PBL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PBL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PBL', N'ON'
GO
ALTER DATABASE [PBL] SET QUERY_STORE = ON
GO
ALTER DATABASE [PBL] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PBL]
GO
/****** Object:  Table [dbo].[MenuItems]    Script Date: 6/9/2024 9:58:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MenuItems](
	[ItemID] [int] NOT NULL,
	[RestaurantID] [int] NULL,
	[Name] [varchar](100) NULL,
	[Description] [text] NULL,
	[Price] [decimal](6, 2) NULL,
	[Category] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 6/9/2024 9:58:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[OrderDetailID] [int] NOT NULL,
	[OrderID] [int] NULL,
	[ItemID] [int] NULL,
	[Quantity] [int] NULL,
	[Subtotal] [decimal](8, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 6/9/2024 9:58:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] NOT NULL,
	[UserID] [int] NULL,
	[RestaurantID] [int] NULL,
	[Date] [date] NULL,
	[TotalAmount] [decimal](8, 2) NULL,
	[Status] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Restaurants]    Script Date: 6/9/2024 9:58:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Restaurants](
	[RestaurantID] [int] NOT NULL,
	[Name] [varchar](100) NULL,
	[Address] [varchar](255) NULL,
	[City] [varchar](255) NULL,
	[Phone] [varchar](15) NULL,
	[OwnerID] [int] NULL,
	[CuisineType] [varchar](50) NULL,
	[Rating] [decimal](3, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[RestaurantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 6/9/2024 9:58:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[Phone] [varchar](15) NULL,
	[Address] [varchar](255) NULL,
	[City] [varchar](225) NULL,
	[UserType] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MenuItems]  WITH CHECK ADD FOREIGN KEY([RestaurantID])
REFERENCES [dbo].[Restaurants] ([RestaurantID])
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD FOREIGN KEY([ItemID])
REFERENCES [dbo].[MenuItems] ([ItemID])
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([RestaurantID])
REFERENCES [dbo].[Restaurants] ([RestaurantID])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Restaurants]  WITH CHECK ADD FOREIGN KEY([OwnerID])
REFERENCES [dbo].[Users] ([UserID])
GO
USE [master]
GO
ALTER DATABASE [PBL] SET  READ_WRITE 
GO
